-- Phase 20 Plan 02 (D-06): der einzige Seed-Block (feature_flags/example_flag)
-- wurde entfernt — die Tabelle faellt mit Migration 020 weg (FEATURES ist jetzt
-- eine Compile-Time-Konstante in packages/shared, keine Supabase-Query mehr).
-- Aktuell keine Seeds noetig.
