/**
 * In-memory mock for expo-sqlite v15 (Node/Jest environment).
 * Implements the subset of the async API used by SqliteAdapter:
 *   openDatabaseAsync, execAsync, runAsync, getFirstAsync, getAllAsync,
 *   withExclusiveTransactionAsync
 *
 * Uses Map-based in-memory storage to simulate SQLite tables.
 * Handles the specific SQL patterns generated by SqliteAdapter.
 */

interface InMemoryDb {
  tables: Map<string, Map<string, Record<string, unknown>>>;
  locked: boolean;
}

// Each openDatabaseAsync call creates a fresh independent database.
// Tests use Date.now() in DB names but may share the same millisecond,
// so we do NOT share state by name — each open call gets a new clean DB.
function createFreshDb(): InMemoryDb {
  return { tables: new Map(), locked: false };
}

class MockSQLiteDatabase {
  constructor(private db: InMemoryDb) {}

  async execAsync(sql: string): Promise<void> {
    const statements = sql.split(';').map((s) => s.trim()).filter(Boolean);
    for (const stmt of statements) {
      this._execute(stmt, []);
    }
  }

  async runAsync(sql: string, ...params: unknown[]): Promise<void> {
    this._execute(sql.trim(), params);
  }

  async getFirstAsync<T>(sql: string, ...params: unknown[]): Promise<T | null> {
    const rows = this._select<T>(sql.trim(), params);
    return rows[0] ?? null;
  }

  async getAllAsync<T>(sql: string, ...params: unknown[]): Promise<T[]> {
    return this._select<T>(sql.trim(), params);
  }

  async withExclusiveTransactionAsync<T>(
    fn: (tx: MockSQLiteDatabase) => Promise<T>,
  ): Promise<T> {
    // Serialize via micro-task loop (sufficient for in-memory mock)
    while (this.db.locked) {
      await new Promise<void>((r) => setImmediate(r));
    }
    this.db.locked = true;
    try {
      return await fn(this);
    } finally {
      this.db.locked = false;
    }
  }

  private _execute(sql: string, params: unknown[]): void {
    if (/^CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s/i.test(sql)) {
      const m = sql.match(/CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+(\w+)/i);
      if (m) this._getTable(m[1]!);
      return;
    }
    if (/^CREATE\s+INDEX/i.test(sql)) return; // no-op
    if (/^DROP\s+/i.test(sql)) return;        // no-op
    if (/^INSERT\s+INTO\s/i.test(sql)) { this._insert(sql, params); return; }
    if (/^UPDATE\s+/i.test(sql)) { this._update(sql, params); return; }
    if (/^DELETE\s+FROM\s+/i.test(sql)) { this._delete(sql, params); return; }
    // Other DDL/DML: silently ignore
  }

  private _insert(sql: string, params: unknown[]): void {
    const tableMatch = sql.match(/INSERT\s+INTO\s+(\w+)\s*\(([^)]+)\)/i);
    if (!tableMatch) return;
    const tableName = tableMatch[1]!;
    const cols = tableMatch[2]!.split(',').map((c) => c.trim());

    const valuesMatch = sql.match(/VALUES\s*\(([^)]+)\)/i);
    if (!valuesMatch) return;

    const placeholders = valuesMatch[1]!.split(',').map((v) => v.trim());
    let pIdx = 0;
    const row: Record<string, unknown> = {};
    for (let i = 0; i < cols.length; i++) {
      const ph = placeholders[i] ?? '';
      row[cols[i]!] = ph === '?' ? (params[pIdx++] ?? null) : (isNaN(Number(ph)) ? ph.replace(/['"]/g, '') : Number(ph));
    }

    const table = this._getTable(tableName);
    // Determine primary key column from ON CONFLICT(col) clause, or fall back to first col
    const conflictColMatch = sql.match(/ON\s+CONFLICT\s*\((\w+)\)/i);
    const pkCol = conflictColMatch ? conflictColMatch[1]! : (cols[0] ?? 'id');
    const pkVal = String(row[pkCol] ?? '');

    const isConflictUpdate = /ON\s+CONFLICT\s*\(\w+\)\s+DO\s+UPDATE\s+SET/i.test(sql);
    if (isConflictUpdate && table.has(pkVal)) {
      // Re-use the new row values for columns mentioned in SET clause (exclude.col pattern)
      // Simplified: for SET col=excluded.col patterns, just replace with new row values
      const setMatch = sql.match(/DO\s+UPDATE\s+SET\s+(.+)$/is);
      if (setMatch) {
        const existing = { ...table.get(pkVal)! };
        const clauses = setMatch[1]!.split(',').map((s) => s.trim());
        for (const clause of clauses) {
          // e.g. "value=excluded.value" or "data=excluded.data"
          const eqIdx = clause.indexOf('=');
          const col = clause.substring(0, eqIdx).trim();
          if (col in row) existing[col] = row[col];
        }
        table.set(pkVal, existing);
      }
    } else {
      table.set(pkVal, row);
    }
  }

  private _update(sql: string, params: unknown[]): void {
    const tableMatch = sql.match(/UPDATE\s+(\w+)\s+SET\s/i);
    if (!tableMatch) return;
    const tableName = tableMatch[1]!;
    const table = this._getTable(tableName);

    const setWhereMatch = sql.match(/SET\s+(.+?)\s+WHERE\s+(.+)$/is);
    if (!setWhereMatch) return;

    let pIdx = 0;
    const setClauses = setWhereMatch[1]!.split(',').map((s) => s.trim());
    const updates: Record<string, unknown> = {};
    for (const clause of setClauses) {
      const eqIdx = clause.indexOf('=');
      const col = clause.substring(0, eqIdx).trim();
      const valPart = clause.substring(eqIdx + 1).trim();
      if (valPart === '?') updates[col] = params[pIdx++] ?? null;
    }

    const whereParts = setWhereMatch[2]!.trim().split(/\s+AND\s+/i);
    const conditions: Array<[string, unknown]> = whereParts.flatMap((part) => {
      const m = part.match(/(\w+)\s*=\s*\?/i);
      return m ? [[m[1]!, params[pIdx++]]] : [];
    });

    for (const [rowId, rowData] of table) {
      if (conditions.every(([col, val]) => rowData[col] === val)) {
        table.set(rowId, { ...rowData, ...updates });
      }
    }
  }

  private _delete(sql: string, params: unknown[]): void {
    const m = sql.match(/DELETE\s+FROM\s+(\w+)(?:\s+WHERE\s+(.+))?$/is);
    if (!m) return;
    const table = this._getTable(m[1]!);
    const whereClause = m[2];
    if (!whereClause) { table.clear(); return; }

    const condMatch = whereClause.match(/(\w+)\s*=\s*\?/i);
    if (condMatch) {
      const col = condMatch[1]!;
      const val = params[0];
      for (const [rowId, rowData] of table) {
        if (rowData[col] === val) table.delete(rowId);
      }
    }
  }

  private _select<T>(sql: string, params: unknown[]): T[] {
    // SELECT <cols> FROM <table> [WHERE ...] [ORDER BY ...] [LIMIT ?]
    const m = sql.match(
      /SELECT\s+(.+?)\s+FROM\s+(\w+)(?:\s+WHERE\s+(.+?))?(?:\s+ORDER\s+BY\s+(.+?))?(?:\s+LIMIT\s+(\d+|\?))?$/is,
    );
    if (!m) return [];

    const table = this._getTable(m[2]!);
    let rows = Array.from(table.values());

    // WHERE — parse conditions once, bind params by position, then filter
    if (m[3]) {
      const conditions = m[3].split(/\s+AND\s+/i);
      // Pre-bind each condition to its param value (params consumed left-to-right once)
      let pIdx = 0;
      type Condition =
        | { kind: 'eq'; col: string; val: unknown }
        | { kind: 'isNull'; col: string }
        | { kind: 'isNotNull'; col: string }
        | { kind: 'pass' };
      const boundConditions: Condition[] = conditions.map((cond) => {
        if (/IS\s+NOT\s+NULL/i.test(cond)) {
          const cm = cond.match(/(\w+)\s+IS\s+NOT\s+NULL/i);
          return cm ? { kind: 'isNotNull' as const, col: cm[1]! } : { kind: 'pass' as const };
        }
        if (/IS\s+NULL/i.test(cond)) {
          const cm = cond.match(/(\w+)\s+IS\s+NULL/i);
          return cm ? { kind: 'isNull' as const, col: cm[1]! } : { kind: 'pass' as const };
        }
        const cm = cond.match(/(\w+)\s*=\s*\?/i);
        if (cm) return { kind: 'eq' as const, col: cm[1]!, val: params[pIdx++] };
        return { kind: 'pass' as const };
      });
      rows = rows.filter((row) =>
        boundConditions.every((cond) => {
          if (cond.kind === 'isNull') return row[cond.col] == null;
          if (cond.kind === 'isNotNull') return row[cond.col] != null;
          if (cond.kind === 'eq') return row[cond.col] === cond.val;
          return true;
        }),
      );
    }

    // ORDER BY
    if (m[4]) {
      const om = m[4].match(/(\w+)\s*(ASC|DESC)?/i);
      if (om) {
        const col = om[1]!;
        const desc = om[2]?.toUpperCase() === 'DESC';
        rows.sort((a, b) => {
          const av = String(a[col] ?? '');
          const bv = String(b[col] ?? '');
          return desc ? bv.localeCompare(av) : av.localeCompare(bv);
        });
      }
    }

    // LIMIT
    if (m[5]) {
      const lv = m[5] === '?' ? (params[params.length - 1] as number) : parseInt(m[5], 10);
      if (!isNaN(lv)) rows = rows.slice(0, lv);
    }

    // Projection
    const colsSpec = m[1]!.trim();
    if (colsSpec === '*') return rows as T[];
    const cols = colsSpec.split(',').map((c) => c.trim());
    return rows.map((row) => {
      const res: Record<string, unknown> = {};
      cols.forEach((c) => { res[c] = row[c]; });
      return res as T;
    }) as T[];
  }

  private _getTable(name: string): Map<string, Record<string, unknown>> {
    if (!this.db.tables.has(name)) this.db.tables.set(name, new Map());
    return this.db.tables.get(name)!;
  }
}

export async function openDatabaseAsync(_name: string): Promise<MockSQLiteDatabase> {
  // Always fresh — each SqliteAdapter instance gets its own isolated in-memory DB.
  return new MockSQLiteDatabase(createFreshDb());
}

export default { openDatabaseAsync };
